---
name: Demo issue

on:
  workflow_dispatch:

jobs:
  demo:
    name: Build and run
    runs-on: ubuntu-20.04

    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Build our problematic container
      run: /bin/bash build.sh

    - name: Debug - Show ownership on the cgroup pre change
      run: ls -ld /sys/fs/cgroup/systemd/system.slice/runner-provisioner.service

    - name: Change ownership on the cgroup
      run: sudo chown -R $(id -un):$(id -gn) /sys/fs/cgroup/systemd/system.slice/runner-provisioner.service

    - name: Debug - Show ownership on the cgroup post change
      run: ls -ld /sys/fs/cgroup/systemd/system.slice/runner-provisioner.service

    - name: Try and run our problematic container with podman
      run: podman run --log-level=debug -d --name deb10 localhost/debian-10-systemd --log-level=debug

    - name: Get debug information about the problematic container and remove
      run: |
        echo ""
        echo "*** Output of podman ps -a"
        podman ps -a
        echo ""
        echo "*** Output of podman logs deb10"
        podman logs deb10
        echo ""
        echo "*** Output of journalctl -r"
        journalctl -r -n 100
        echo ""
        echo "*** Stop and remove the container"
        podman stop deb10
        podman rm deb10

    - name: Output debug info
      run: |
        echo ""
        echo "*** Output of 'podman version':"
        podman version
        echo ""
        echo "*** Output of 'podman info --debug':"
        podman info --debug
        echo ""
        echo "*** Output of 'apt list podman'"
        apt list podman
        echo ""
        echo "*** Output of 'buildah version'"
        buildah version
        echo ""
