---
name: Demo issue

on:
  workflow_dispatch:

jobs:
  demo:
    name: Build and run
    runs-on: ubuntu-20.04

    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Build our problematic container
      run: /bin/bash build.sh

    - name: Try and run our problematic container with podman
      run: podman run --log-level=debug -d --name deb10 localhost/debian-10-systemd

    - name: Get debug information about the problematic container and remove
      run: |
        echo ""
        echo "*** Output of podman ps"
        podman ps -a
        echo ""
        echo "*** Output of podman logs deb10"
        podman logs deb10
        echo ""
        echo "*** Output of journalctl -r"
        journalctl -r
        echo ""
        echo "*** Remove the container"
        podman rm deb10

    - name: Show we can run the container using 'sudo podman'
      run: |
        echo ""
        echo "*** Build the image using 'sudo buildah'"
        sudo /bin/bash build.sh
        echo ""
        echo "*** Run the container"
        sudo podman run --log-level=debug -d --name deb10 localhost/debian-10-systemd
        echo ""
        echo "*** Show the container is running"
        sudo podman ps -a
        echo ""
        echo "*** Stop and remove the running container"
        sudo podman stop deb10
        sudo podman rm deb10

    - name: Output debug info
      run: |
        echo ""
        echo "*** Output of 'podman version':"
        podman version
        echo ""
        echo "*** Output of 'podman info --debug':"
        podman info --debug
        echo ""
        echo "*** Output of 'apt list podman'"
        apt list podman
        echo ""
        echo "*** Output of 'buildah version'"
        buildah version
        echo ""
